[package]
name = "packet_strider"
version = "0.1.0"
authors = ["Rick"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.33"
pcap-parser = "0.10.0"
etherparse = "0.9.0"
ssh-parser = "0.4.0"
md5 = "0.7.0"